---
title: "timing_results"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{timing_results}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Several functions were written for this package. In the "estimation" category, the functions are
- `outer_hle2(x, y)`
- 'cpp_hle2(x, y)'
These perform identical functions within the package, namely estimating the shift of the location parameter of 
two distributions. We will now test how fast each is.

```{r setup}
library(datar)
```

```{r data}
results <- data.frame(
  outer_time.user = double(),
  outer_time.sys = double(),
  outer_time.elap = double(),
  cpp_time.user = double(),
  cpp_time.sys = double(),
  cpp_time.elap = double()
  )
time_exp <- function(n, mean1, mean2){
  x <- rexp(n, (1/mean1))
  y <- rexp(n, (1/mean2))

  outer_time <- system.time(outer_hle2(x,y))
  outer_time <- data.frame(
    user = outer_time[1],
    sys = outer_time[2],
    elap = outer_time[3])
  cpp_time <- system.time(cpp_hle2(x,y))
  cpp_time <- data.frame(
    user = cpp_time[1],
    sys = cpp_time[2],
    elap = cpp_time[3])


  return(data.frame(outer_time = outer_time, cpp_time = cpp_time))
}

for(i in seq_len(30)){
  results <- rbind(results, time_exp(10000, 5, 10))
  }


```




