# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' cpp_median
#' 
#' @description
#' Find the median of a numeric vector
#' 
#' @details
#' Using the c++ function `nth_element`, this function places the element which,
#' if the vector were sorted, would be in the middle position and then returns that same element
#' 
#' @param vec The numeric vector of which to take the median
#' 
#' @returns Numeric of median
#'
#' @examples{
#' library(datar)
#' x <- rnorm(100, 10) 
#' cpp_median(x)
#' }
#' @references
#' DATA495 lectures with Prof. Kloke. 
#' 
#' @aliases Median
#' @export
cpp_median <- function(vec) {
    .Call(`_datar_cpp_median`, vec)
}

#' cpp_hle1
#' 
#' @description
#' Compute the Hodges-Lehmann estimate of location
#' 
#' @details
#' Using the function `cpp_median` this function computes the Hodges-Lehmann estimator of location.
#' This function cannot allocate a vector of the correct size if the number of measurements exceeds 
#' 40,000 and so, throws an error. 
#' 
#' @param vec The numeric vector of which find the Hodges-Lehmann location estimator
#' 
#' @returns Numeric representing the Hodges-Lehmann location estimator
#'
#' @examples{
#' library(datar)
#' x <- rnorm(100, 10) 
#' datar::cpp_hle1(x)
#'}
#' @references
#' DATA495 lectures with Prof. Kloke. 
#' 
#' @seealso [outer_hle1()] The base-R implementation of HLE1
#'
#' @aliases HLE1
#' @export
cpp_hle1 <- function(vec) {
    .Call(`_datar_cpp_hle1`, vec)
}

#' cpp_hle2
#' 
#' @description
#' Compute the Hodges-Lehmann estimate of shift
#' 
#' @details
#' Using the function `cpp_median` this function computes the Hodges-Lehmann estimator of shift.
#' This function cannot allocate a vector of the correct size if the number of measurements exceeds 
#' 40,000 and so, throws an error. 
#' 
#' @param x Numeric vector of measurements from the first population
#' 
#' @param y Numeric vector of measurements from the second population
#' 
#' @returns Numeric representing the Hodges-Lehmann estimator of shift
#'
#' @examples{
#' library(datar)
#' x <- rnorm(100, 10) 
#' y <- rnorm(100, 5) 
#' datar::cpp_hle2(x, y)
#'}
#' @references
#' DATA495 lectures with Prof. Kloke. 
#' 
#' @seealso [outer_hle2()] The base-R implementation of HLE2
#'
#' @aliases HLE2
#' @export
cpp_hle2 <- function(x, y) {
    .Call(`_datar_cpp_hle2`, x, y)
}

