# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

median <- function(vec) {
    .Call(`_datar_median`, vec)
}

cpp_hle2 <- function(x, y) {
    .Call(`_datar_cpp_hle2`, x, y)
}

cpp_hle1 <- function(x) {
    .Call(`_datar_cpp_hle1`, x)
}
